speakers:
  al: Andres_Laansoo
  ao: A_Ots_loeng
  hv: Helina_Vigla
  jp: Janek_Popell
  mk: Maarja_Kruusmaa
  ms: Margit_Suurna
  mj: Mati_Jarvis
  mr: Rillo_loeng
  th: Tea_Hunt_KG_Loeng

files:
  wav: "train.wav-list"
#  trns: "/teamwork/t40511_asr/c/estonian-speech/train.verbatim.trn"
  trn: "train.verbatim.trn"
  mv_directory: "/teamwork/t40511_asr/c/martti_vainio/mv_original"

params:
  seconds: "1000"
